### ISSUE TITLE
エラーメッセージの改善2

### ISSUE THREAD

**Issue by daiksud** [textlint-ja/textlint-rule-no-mix-dearu-desumasu#49]
# 概要

優先したい表記を "である" または "ですます" で指定（固定）した場合に、エラーメッセージの内容が分かりづらく、混乱します。チームメンバーがエラーを解消できず、「なぜエラーなのか分かりません。どうすればいいですか？」とよく聞かれます。

改善した方が良いかなと考えています。

related #21 

## 詳細

弊チームで [textlint-rule-preset-ja-technical-writing](https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing) を採用させていただいているのですが、こちらのプリセットによる`no-mix-dearu-desumasu`の設定は、デフォルトが以下となっています。

```
"preferInHeader": "",
"preferInBody": "ですます",
"preferInList": "である",
"strict": false
```

この設定のとき、例えば箇条書きで "ですます"調 だけを使用しても、以下のようなエラーが出ます。

```
ja-technical-writing/no-mix-dearu-desumasu: 箇条書き: "である"調 と "ですます"調 が混在
=> "である"調 の文体に、次の "ですます"調 の箇所があります: "ます"
Total:
である  : 0
ですます: 3
```

箇条書きなので "である" で統一する必要があるのですが、このエラーを見た人は最初の `"である"調 と "ですます"調 が混在` だけを読み、「ああ、どっちかに統一すればいいのね」と思うようです。

そして、「"である" 0 なのに混在だとエラーが出て、どうすればいいのか分かりません」とよく聞かれます。

## 改善案

「混在」という単語が誤解の引き金になっていると感じます。どちらかだけを明示できないかなと思います。

```
ja-technical-writing/no-mix-dearu-desumasu: 箇条書きが "である"調 になっていない
=> "である"調 であるべき文体に、次の "ですます"調 の箇所があります: "ます"
```

```
ja-technical-writing/no-mix-dearu-desumasu: 本文が "ですます"調 になっていない
=> "ですます"調 であるべき文体に、次の "である"調 の箇所があります: "ある"
```

## 備考

自分でやれそうだったら、PR出します。

**Comment by azu** [comment]
preferの指定がある場合(`""`ではない場合)は、どちらかに明示するのは良い気がします

**Comment by daiksud** [comment]
ありがとうございます。ちょっとチャレンジしてみます。
